url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/3d-foam-letters" 
title: "" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss

postcss:
  cache: false
 